version: "3.9"

services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: postgres
      POSTGRES_HOST: db
    ports:
      - "3000:3000"

  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
